# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Stats Text File

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # This allows git push via GITHUB_TOKEN

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run your code 
      run: |
        mkdir -p info
        python generate_stat_summary.py > info/stats.txt
        python generate_tsv_from_kb.py -t > info/techniques.txt
        python generate_tsv_from_kb.py -w > info/weaknesses.txt
        python generate_tsv_from_kb.py -m > info/mitigations.txt
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add info/stats.txt
        git add info/techniques.txt
        git add info/weaknesses.txt
        git add info/mitigations.txt
        git commit -m "Update stats [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
